fix: false              # default: false
parallel: false         # default: false
format: progress        # default: Standard::Formatter
ruby_version: 2.6.5     # default: RUBY_VERSION
default_ignores: false  # default: true

# ignore:                 # default: []
#   - 'db/schema.rb'
#   - 'vendor/**/*'
#   - 'test/**/*':
#     - Layout/AlignHash
